#! /bin/bash
: ${SRC:=/}
: ${DUPLICITY:=duplicity}
: ${BACKUP_HOST:=nasobem.local}
: ${BACKUP:=/net/${BACKUP_HOST}/c/backup/apollon.dup}
: ${CACHE:=/root/.cache/duplicity}
: ${CONF:=/root}
: ${NAME:=apollon.dup}
: ${KEY:=63D76654}
: ${OPTS:="--volsize 500 -v5 --allow-source-mismatch"}
: ${DRY:=--dry-run}
: ${FULL:=}
: ${ACTION:=backup}
: ${INTERVAL:=$((3600*4-30))}
: ${DEBUG:=0}
LOG=$BACKUP/backup.log

[ $UID -eq 0 ] || exec sudo "$0" "$@"
export LC_ALL=C

ERROR='cry Error executing \""$BASH_COMMAND" at $0:$LINENO\" >&2'
CLEANUP=''
ERRCODE=129

trap 'trap - ERR; eval "$ERROR"' ERR
trap 'trap - 0; eval "$CLEANUP"' 0

timestamp() { date +%Y-%m-%d.%H:%M:%S; }
cry() { echo "== $0: $@ ==" >&2; };
die() { cry FATAL: "$@"; exit $ERRCODE; }
cmd() {
    cry "$@"
    eval "$@"
}

set -e
set -E
[[ $# -le 1 || ( $# -eq 2 && x$1 = xrestore ) ]]

# Try to resolve and ping the host, give up otherwise
IP=$(dig +short "$BACKUP_HOST")
[[ -n "$IP" ]] || IP=$(avahi-resolve -n "$BACKUP_HOST" | cut -f 2)
[[ -n "$IP" ]]
ping -c 1 "$IP" &>/dev/null

[[ -d "$SRC" ]]
[[ -d "$BACKUP" ]]

case $1 in
    back)
	DRY=
	;;
    full)
	DRY=
	FULL=full
	;;
    list|restore)
	ACTION=$1
	shift
	;;
    "") ;;
    *)  die usage: "$0 [back]";; 
esac    

case $ACTION in
    list)
	cmd $DUPLICITY list-current-files --archive-dir "$CACHE" --name "$NAME" --encrypt-key "$KEY" file://"$BACKUP"
	exit 0
	;;
    restore)
	TRG=$(mktemp -d /tmp/back-XXXXXX)
	if [[ $1 ]]; then
	    ARGS="--file-to-restore \"$1\""
	else
	    ARGS=
	fi
	cry restoring to $TRG
	cmd $DUPLICITY restore $ARGS --archive-dir "$CACHE" --name "$NAME" --encrypt-key "$KEY" file://"$BACKUP" "$TRG"
	exit 0
	;;
esac

last=$(ls -t "$CACHE/$NAME"/*.manifest 2>/dev/null | head -1)
if [[ -f "$last" ]]; then
    ts=$(stat -c %Y "$last")
    now=$(date +%s)
    if [[ $((now - ts < INTERVAL)) -eq 1 ]]; then
	[[ $DEBUG -eq 0 ]] || cry "Last backup is $((now-ts))s < ${INTERVAL}s old, exiting."
	exit 0
    fi
else
    [[ -n "$FULL" ]] || { die "incremental update requested but no previous backup found"; }
fi

if [[ -z "$DRY" ]]; then
    if tty >/dev/null; then
	cry REAL RUN, last chance to exit
	sleep 5
    fi
    [[ $DEBUG -le 0 ]] || cry log file is $LOG
    exec >>$LOG 2>&1
fi

cry Started at $(timestamp)
CLEANUP='cry Finished at $(timestamp);'"$CLEANUP"

TMPDIR=$(mktemp -d /tmp/back-XXXXXX)
CLEANUP='rm -rf $TMPDIR;'"$CLEANUP"

includelist() {
    rm -f "$1"
    [ -f $CONF/.backup.include.early ] && cat $CONF/.backup.include.early \
	>>"$1"
    echo "- $CACHE/$NAME" >>$1
    cat >>"$1" <<\EOF
- /.snapshots
- /suse
- /mounts
- /net
- /proc
- /sys
- /dev
- /tmp
- /run
- /var/run
- /mnt/vms
- /mnt/git
- /**/.DCOPserver_*
- /**/.beagle
- /**/.aMule
- /**/.cddb
- /**/.compiz/session
- /**/.config/Blue Jeans
+ /home/*/.config/libreoffice/*/user/config
- /**/.config/libreoffice/*
- /**/.config/google-chrome/Crash*
- /**/.config/google-chrome/*/Cookies
- /**/.config/google-chrome/*/Extensions
- /**/.config/pulse/*.conf
- /**/.config/pulse/*.pa
- /**/.config/pulse
- /**/.dbus/session-bus
- /**/.dropbox
- /**/.dropbox-dist
- /**/.dvdcss
- /**/.ee
- /**/.emacs.d/auto-save-list
- /**/.fontconfig/*.cache*
- /**/.java/deployment/log
- /**/.java/deployment/tmp
- /**/.gnome2/totem-addons
- /**/.kde4/share/apps/ktorrent/tor*
- /**/.kde4/share/apps/okular/docdata
- /**/.kde4/share/apps/gwenview/recentfolders
- /**/.kde4/share/apps/gwenview/recenturls
- /**/.kde/share/apps/kget/logs
- /**/.kde/share/apps/kpdf
- /**/.kde/share/apps/ktorrent/tor*
- /**/.kde/share/apps/kconf_update/log
- /**/.kde/tmp-*
- /**/.mcop/trader-cache
- /**/.mythtv/themecache
- /**/.mozilla/*/Crash Reports
- /**/.local/share/zeitgeist
- /**/.local/share/shotwell/data
- /**/.local/share/gnome-do
- /**/.local/share/gnome-shell/extensions
- /**/.local/share/gnome-software
- /**/.local/share/icons
- /**/.local/share/gvfs-metadata
- /**/.local/share/tracker/data
- /**/.macromedia/Flash_Player
- /**/.mozilla/*/extensions
- /**/.mozilla/Crash*
- /**/.mozilla/firefox/*/datareporting
- /**/.mozilla/firefox/*/saved-telemetry-pings
- /**/.mozilla/firefox/*/extensions
- /**/.mozilla/firefox/*/webapps
- /**/.mozilla/firefox/*/webappsstore.*
- /**/.mozilla-thunderbird/*/extensions
- /**/.mozilla-thunderbird/*/saved-telemetry-pings
- /**/.mozilla-thunderbird/Crash*
- /**/.thunderbird/*/extensions
- /**/.thunderbird/*/saved-telemetry-pings
- /**/.thunderbird/Crash*
- /**/.pulse
- /**/.purple/logs
- /**/.xauth*
- /**/.Private
- /**/.texmf-var
- /**/.**.scantemp.pnm
- /**/.**.previewtemp.pnm
- /**/.**[cC]ache
- /**/.**[tT]rash
- /**/.**[tT]humbnails
- /**/Dropbox
- /**/gtk-gnutella-downloads
- /home/*/Downloads
- /home/*/Music
- /home/*/Musik
- /home/*/Photos
- /home/*/Videos
- /home/*/rpmbuild
- /root/Downloads
- /etc/X11/xkb
- /etc/texmf/ls-R
- /etc/bootsplash/themes
- /etc/brltty
- /etc/gufw/app_profiles
- /etc/sane.d
- /etc/usb_modeswitch.d
- /etc/xscreensaver
- /var/log/cups
- /var/log/gdm*.[1-9]
- /var/log/journal
- /var/log/*20[0-9][0-9][0-9][0-9][0-9][0-9]
- /var/log/*20[0-9][0-9][0-9][0-9][0-9][0-9].gz
- /var/log/*20[0-9][0-9][0-9][0-9][0-9][0-9].bz2
- /var/log/*20[0-9][0-9][0-9][0-9][0-9][0-9].xz
- /var/log/**/*20[0-9][0-9][0-9][0-9][0-9][0-9]
- /var/log/**/*20[0-9][0-9][0-9][0-9][0-9][0-9].gz
- /var/log/**/*20[0-9][0-9][0-9][0-9][0-9][0-9].bz2
- /var/log/**/*20[0-9][0-9][0-9][0-9][0-9][0-9].xz
- /var/log/*.[0-9]
- /var/log/*.[0-9].gz
- /var/log/upstart/*.[0-9]
- /var/log/upstart/*.[0-9].gz
- /var/log/messages-*.bz2
- /var/log/NetworkManager-*.bz2
- /var/log/ntpstats
- /var/log/peerstats
- /var/log/updateTestcase*
- /var/log/zypper.log-*.bz2
- /NoBackup
- /**/NoBackup
- /**/*.iso
- /**/*.a
- /**/*.o
- /**/*~
- /**/.gvfs
- /**/.#*
- /**/#*
- /**/*.pyc
+ /usr/local
+ /var/mail
+ /var/log
+ /etc
+ /root
+ /home
- /*
EOF

    if [ -f $CONF/.backup.include.late ]; then
	cat $CONF/.backup.include.late >>"$1"
    fi
}

includelist "$TMPDIR/include.txt"
[[ $DEBUG -eq 0 ]] || cat "$TMPDIR/include.txt"
cmd $DUPLICITY $FULL $DRY $OPTS --exclude-globbing-filelist "$TMPDIR/include.txt" --archive-dir "$CACHE" --name $NAME --encrypt-key $KEY "$SRC" file://"$BACKUP"
